/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

/* Define Addresses */
// RCC Base: 0x44020C00
// GPIOF Base: 0x42021400

#define GPIOF_MODER (uint32_t*) 0x42021400
#define GPIOF_ODR (uint32_t*) (0x42021400 + 0x14)
#define RCC_AHB2ENR (uint32_t*) (0x44020C00 + 0x08C)




int main(void)
{
	 /* Initialize values */
	    *(RCC_AHB2ENR) = 0xC0000020; // set bit 5 to 1 to enable clocking to port F
	    *(GPIOF_MODER) = 0x0100;     // set I/O direction of pin F4 to general purpose output (bits 9 & 8 set to 0 & 1)

	    /* Continuously turn LED on and off */

	    while (1) {
	            *(GPIOF_ODR) = 0x0010; // turn LED at F4 on (set bit 4 to 1)
	            for (int i = 0; i < 1000000; ++i) {;}
	            *(GPIOF_ODR) = 0x0000; // turn LED off (set bit 4 to 0)
	            for (int i = 0; i < 1000000; ++i) {;}
	        }

}
