/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Register Addresses */
#define RCC_AHB2ENR   ((volatile uint32_t*) 0x44020C8C)

#define GPIOB_MODER   ((volatile uint32_t*) 0x42020400) // Green
#define GPIOB_ODR     ((volatile uint32_t*) 0x42020414)

#define GPIOF_MODER   ((volatile uint32_t*) 0x42021400) // Yellow
#define GPIOF_ODR     ((volatile uint32_t*) 0x42021414)

#define GPIOG_MODER   ((volatile uint32_t*) 0x42021800) // Red
#define GPIOG_ODR     ((volatile uint32_t*) 0x42021814)

int main(void) {
    /* 1. Enable Clocks for Ports B, F, and G */
    // Bit 1 = Port B, Bit 5 = Port F, Bit 6 = Port G
    *RCC_AHB2ENR |= (1 << 1) | (1 << 5) | (1 << 6);

    /* 2. Configure Pins as General Purpose Output */
    // Green (PB0): Bits 1:0 = 01
    *GPIOB_MODER &= ~(3 << 0);
    *GPIOB_MODER |=  (1 << 0);

    // Yellow (PF4): Bits 9:8 = 01
    *GPIOF_MODER &= ~(3 << 8);
    *GPIOF_MODER |=  (1 << 8);

    // Red (PG4): Bits 9:8 = 01
    *GPIOG_MODER &= ~(3 << 8);
    *GPIOG_MODER |=  (1 << 8);

    /* 3. Main Blink Loop */
    while (1) {
        // Turn ALL LEDs ON
        *GPIOB_ODR |= (1 << 0); // Green
        *GPIOF_ODR |= (1 << 4); // Yellow
        *GPIOG_ODR |= (1 << 4); // Red

        for (volatile int i = 0; i < 500000; i++);

        // Turn ALL LEDs OFF
        *GPIOB_ODR &= ~(1 << 0);
        *GPIOF_ODR &= ~(1 << 4);
        *GPIOG_ODR &= ~(1 << 4);

        for (volatile int i = 0; i < 500000; i++);
    }
}
