/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Register Addresses for STM32H563ZITx */
#define RCC_AHB2ENR   ((volatile uint32_t*) 0x44020C8C)
#define GPIOG_MODER   ((volatile uint32_t*) 0x42021800)
#define GPIOG_ODR     ((volatile uint32_t*) 0x42021814)

int main(void) {
    /* 1. Enable Clock for Port G */
    // Bit 6 corresponds to GPIOG in the AHB2ENR register
    *RCC_AHB2ENR |= (1 << 6);

    /* 2. Configure PG4 as Output */
    // MODER uses 2 bits per pin. Pin 4 uses bits 9 and 8.
    // Setting bits 9:8 to "01" makes it a General Purpose Output.
    *GPIOG_MODER &= ~(3 << 8); // Clear bits 9 and 8
    *GPIOG_MODER |=  (1 << 8); // Set bit 8 to 1

    /* 3. Blink Loop */
    while (1) {
        // Set Pin 4 HIGH (Turn LED ON)
        *GPIOG_ODR |= (1 << 4);

        // Delay loop (volatile prevents compiler from optimizing it away)
        for (volatile int i = 0; i < 500000; i++);

        // Set Pin 4 LOW (Turn LED OFF)
        *GPIOG_ODR &= ~(1 << 4);

        // Delay loop
        for (volatile int i = 0; i < 500000; i++);
    }

    return 0;
}
