/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Peripheral Addresses */
#define RCC_AHB2ENR   ((volatile uint32_t*) 0x44020C8C)
#define GPIOB_MODER   ((volatile uint32_t*) 0x42020400) // Green
#define GPIOB_ODR     ((volatile uint32_t*) 0x42020414)
#define GPIOF_MODER   ((volatile uint32_t*) 0x42021400) // Yellow
#define GPIOF_ODR     ((volatile uint32_t*) 0x42021414)
#define GPIOG_MODER   ((volatile uint32_t*) 0x42021800) // Red
#define GPIOG_ODR     ((volatile uint32_t*) 0x42021814)

int main(void) {
    /* 1. Enable Clocks for Ports B, F, and G */
    *RCC_AHB2ENR |= (1 << 1) | (1 << 5) | (1 << 6);

    /* 2. Configure Pins as Outputs (01 in MODER) */
    *GPIOB_MODER = (*GPIOB_MODER & ~(3 << 0)) | (1 << 0); // PB0 (Green)
    *GPIOF_MODER = (*GPIOF_MODER & ~(3 << 8)) | (1 << 8); // PF4 (Yellow)
    *GPIOG_MODER = (*GPIOG_MODER & ~(3 << 8)) | (1 << 8); // PG4 (Red)

    /* 3. Traffic Light Loop */
    while (1) {
        // STEP 1: GREEN ONLY
        *GPIOB_ODR |=  (1 << 0); // Green ON
        *GPIOF_ODR &= ~(1 << 4); // Yellow OFF
        *GPIOG_ODR &= ~(1 << 4); // Red OFF
        for (volatile int i = 0; i < 2000000; i++); // Long Delay

        // STEP 2: YELLOW ONLY
        *GPIOB_ODR &= ~(1 << 0); // Green OFF
        *GPIOF_ODR |=  (1 << 4); // Yellow ON
        *GPIOG_ODR &= ~(1 << 4); // Red OFF
        for (volatile int i = 0; i < 800000; i++);  // Shorter Delay

        // STEP 3: RED ONLY
        *GPIOB_ODR &= ~(1 << 0); // Green OFF
        *GPIOF_ODR &= ~(1 << 4); // Yellow OFF
        *GPIOG_ODR |=  (1 << 4); // Red ON
        for (volatile int i = 0; i < 2000000; i++); // Long Delay
    }
}
