/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Addresses for STM32H563ZITx */
#define RCC_AHB2ENR   ((volatile uint32_t*) 0x44020C8C)
#define GPIOB_MODER   ((volatile uint32_t*) 0x42020400)
#define GPIOB_ODR     ((volatile uint32_t*) 0x42020414)

int main(void) {
    /* 1. Enable Clock for Port B */
    // Bit 1 enables the GPIOB peripheral clock
    *RCC_AHB2ENR |= (1 << 1);

    /* 2. Configure PB0 as Output */
    // Pin 0 uses bits 1:0. Set to "01" for General Purpose Output.
    *GPIOB_MODER &= ~(3 << 0); // Clear bits 1 and 0
    *GPIOB_MODER |=  (1 << 0); // Set bit 0 to 1

    /* 3. Blink Loop */
    while (1) {
        // Turn Green LED ON (Set PB0 bit 0 to 1)
        *GPIOB_ODR |= (1 << 0);
        for (volatile int i = 0; i < 500000; i++);

        // Turn Green LED OFF (Set PB0 bit 0 to 0)
        *GPIOB_ODR &= ~(1 << 0);
        for (volatile int i = 0; i < 500000; i++);
    }
}
